// Close-up of the player avatar from the front and side.
import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import { extname, join } from "node:path";
import { chromium } from "playwright";
const ROOT = new URL("..", import.meta.url).pathname;
const TYPES = { ".html":"text/html",".js":"text/javascript",".css":"text/css",".json":"application/json",".webmanifest":"application/manifest+json",".wasm":"application/wasm",".svg":"image/svg+xml",".png":"image/png" };
const server = createServer(async (req,res)=>{try{let p=decodeURIComponent(req.url.split("?")[0]);if(p==="/")p="/index.html";const b=await readFile(join(ROOT,p));res.writeHead(200,{"content-type":TYPES[extname(p)]||"application/octet-stream"});res.end(b);}catch{res.writeHead(404);res.end("nf");}});
await new Promise(r=>server.listen(0,r));
const port=server.address().port;
const browser=await chromium.launch({executablePath:"/opt/pw-browsers/chromium-1194/chrome-linux/chrome",args:["--no-sandbox","--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]});
const page=await browser.newPage({viewport:{width:720,height:760}});
page.on("pageerror",e=>console.log("PAGEERR",e.message));
await page.goto(`http://127.0.0.1:${port}/`,{waitUntil:"load"});
await page.waitForSelector("#menu:not(.hidden)",{timeout:30000});
await page.evaluate(()=>document.getElementById("play-btn").click());
await page.waitForTimeout(600);
await page.evaluate(()=>BABYLON.Engine.LastCreatedEngine.stopRenderLoop());
const frame=(px,py,pz,tx,ty,tz)=>page.evaluate(([px,py,pz,tx,ty,tz])=>{const sc=BABYLON.Engine.LastCreatedEngine.scenes[0],h=sc.getMeshByName("hero"),cam=sc.activeCamera;cam.position=new BABYLON.Vector3(h.position.x+px,h.position.y+py,h.position.z+pz);cam.setTarget(new BABYLON.Vector3(h.position.x+tx,h.position.y+ty,h.position.z+tz));sc.render();sc.render();},[px,py,pz,tx,ty,tz]);
await frame(0,0.55,2.4,0,0.4,0); await page.screenshot({path:join(ROOT,"scripts","avatar-front.png")});
await frame(0,1.0,1.5,0,0.65,0); await page.screenshot({path:join(ROOT,"scripts","avatar-head.png")});
await frame(2.2,0.55,0.6,0,0.4,0); await page.screenshot({path:join(ROOT,"scripts","avatar-side.png")});
await browser.close();server.close();
console.log("saved avatar shots");
